services:
  # Scripting
  nodered:
    # build:
    #     dockerfile: Dockerfile
    # image: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    ports:
      - 1880:1880
    volumes:
      - ./configuration/nodered/settings.js:/data/settings.js
    networks:
      - iotstack
  
  # MQTT
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes: 
      - ./configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./configuration/mosquitto/password.txt:/mosquitto/config/password.txt
    networks:
      - iotstack
  
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: unless-stopped
    ports:
      - "1884:1883"     # MQTT
      - "8084:8083"     # MQTT over WebSocket
      - "18083:18083"   # Dashboard
    environment:
      - TZ=Asia/Kuala_Lumpur
      - EMQX_NAME=emqx
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=password
    networks:
      - iotstack
  
  # Database and DBMS
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Kuala_Lumpur
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=iot
    ports:
      - 3306:3306
    networks:
      - iotstack
  adminer:
    image: adminer:latest
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8060:8080
    networks:
      - iotstack

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Kuala_Lumpur
    networks:
      - iotstack

  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Kuala_Lumpur
    networks:
      - iotstack

  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    environment:
    - TZ=Asia/Kuala_Lumpur
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=password
    - DOCKER_INFLUXDB_INIT_ORG=my-organisation
    - DOCKER_INFLUXDB_INIT_BUCKET=iot-sensors
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=A8C2B071-35F6-43F8-9F51-C5F584B2366B
    - DOCKER_INFLUXDB_INIT_MODE=setup
    ports:
      - '8086:8086'
    healthcheck:
      test: ['CMD', 'influx', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - iotstack
  
  # Dashboard
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - TZ=Asia/Kuala_Lumpur
    ports:
      - '3000:3000'
    networks:
      - iotstack
  
  # LoRaWAN Network Server
  chirpstack:
    image: chirpstack/chirpstack:latest
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
      - ./configuration/lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - TZ=Asia/Kuala_Lumpur
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - 8080:8080
    networks:
      - iotstack

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:latest
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - TZ=Asia/Kuala_Lumpur
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=as923/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=as923/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=as923/gateway/{{ .GatewayID }}/command/#
    depends_on:
      - mosquitto
    networks:
      - iotstack
  
  chirpstack-gateway-bridge-basicstation:
    image: chirpstack/chirpstack-gateway-bridge:latest
    restart: unless-stopped
    command: -c /etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge-basicstation-as923.toml
    environment:
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 3001:3001
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto
    networks:
      - iotstack

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:latest
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    environment:
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 8090:8090
    depends_on:
      - chirpstack
    networks:
      - iotstack

networks:
  iotstack:
    driver: bridge
